all: tests run

tests:
	perl src/gen-tests.pl src/test.c x

run:
	perl src/regress.pl -v $(BINS) < regress.in

clean:
	rm -f *.[iso] *.s.* x*c.c *.out *.err core *~

clean-all: clean
	rm -f $(BINS) x*.c

%: %.tc
	$(CC) $(CFLAGS) -o $@ $^
%: %.c
	$(CC) $(CFLAGS) -o $@ $^

%: %.o
	$(CC) $(CFLAGS) -o $@ $^
